[project]
name = "single-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-ollama>=0.2.3",
    "langgraph>=0.3.5",
    "ollama>=0.4.7",
    "ruff>=0.9.10",
]
